apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: camunda-cloud-provider-secret
type: Opaque
data:
  # credentials: BASE64ENCODED_PROVIDER_CREDS in the format of: { "ccClientId": "asd", "ccSecretId": "123"}
---
apiVersion: camunda.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: camunda-cloud
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: camunda-cloud-provider-secret
      key: credentials
